graph LR
  AppModule-->WinstonModule
  WinstonModule-->PrismaModule
  PrismaModule-->WinstonModule
  PrismaModule-->ConfigHostModule
  ConfigHostModule-->WinstonModule
  ConfigHostModule-->PrismaModule
  WinstonModule-->ConfigHostModule
  AppModule-->AuthenticationModule
  AuthenticationModule-->PrismaModule
  AuthenticationModule-->PassportModule
  PassportModule-->WinstonModule
  PassportModule-->PrismaModule
  PassportModule-->ConfigHostModule
  AuthenticationModule-->JwtModule
  JwtModule-->ConfigModule
  ConfigModule-->ConfigHostModule
  ConfigModule-->WinstonModule
  ConfigModule-->PrismaModule
  JwtModule-->WinstonModule
  JwtModule-->PrismaModule
  JwtModule-->ConfigHostModule
  AuthenticationModule-->ConfigModule
  AuthenticationModule-->ProfileModule
  ProfileModule-->WinstonModule
  ProfileModule-->PrismaModule
  ProfileModule-->ConfigHostModule
  AuthenticationModule-->WinstonModule
  AuthenticationModule-->ConfigHostModule
  AppModule-->PrismaModule
  AppModule-->UsersModule
  UsersModule-->WinstonModule
  UsersModule-->PrismaModule
  UsersModule-->ConfigHostModule
  AppModule-->ProfileModule
  AppModule-->PostModule
  PostModule-->WinstonModule
  PostModule-->PrismaModule
  PostModule-->ConfigHostModule
  AppModule-->RolesModule
  RolesModule-->WinstonModule
  RolesModule-->PrismaModule
  RolesModule-->ConfigHostModule
  AppModule-->ConfigHostModule
